### ISSUE TITLE
Getting error in service now while importing this code from source control

### ISSUE THREAD

**Issue by bhuvan309** [ServiceNow/devtraining-needit-newyork#14]
Getting an error when importing the fork version of this file from service now source control.
Please provide the steps to fix this issue.
> Repository contains an Application that does not match the Repository Configuration record

<img width="561" alt="LinkToSourceControlErrror" src="https://user-images.githubusercontent.com/56302654/66431474-c5a58180-ea67-11e9-93b3-0a7c9385bb07.PNG">

**Comment by bhuvan309** [comment]
My bad, I was linking it rather importing. The issue is resolved now.

**Comment by niedziel** [comment]
Thank you for letting us know you got it sorted out.  Happy developing!
