### ISSUE TITLE
Unable to download my clone

### ISSUE THREAD

**Issue by bhushanbhosale** [ServiceNow/devtraining-needit-newyork#97]
I had checked in my code to github 4 months ago. Now I'm trying to import using servicenow instance. It is not importing my version rather it is importing base version of devtraing-needit-newyork branch.

Please help.

**Comment by bsweets** [comment]
Please send us feedback asking for help from one of the learning pages you are trying to complete while authenticated to the Developer Site. Your feedback will open a task for us so we can track that we helped you and let us know your PDI so we can best help you here.
